const FLICKR_USER_ID="";
const FLICKR_API_KEY = "";
const FLICKR_SECRET = "";
const FLICKR_ACCESS_TOKEN="";
const FLICKR_ACCESS_TOKEN_SECRET="";

module.exports = {FLICKR_ACCESS_TOKEN, FLICKR_ACCESS_TOKEN_SECRET, FLICKR_USER_ID, FLICKR_API_KEY, FLICKR_SECRET}